### PR TITLE
Defines failure_message_when_negated and fixes #13

### LINKED ISSUE #13: failure_message_when_negated is undefined
It seems like there is a typo in `enqueue_a.rb`. Instead of `failure_message_when_negated`, it defines `failure_message_negated`. As a result, if you run a negative assertion, it results in `undefined method failure_message_when_negated`.

### PR DESCRIPTION
**Pull request by swastik**

### CODE REVIEW

**Comment by isaacseymour** [comment]
Awesome, thanks @swastik

**Comment by lleger** [comment]
I upgraded to 0.4.1 and got the `undefined method `failure_message_when_negated'` error. I thought I was crazy, but if you [download the gem](https://rubygems.org/downloads/rspec-activejob-0.4.1.gem) from RubyGems, it doesn't include this change. I opened the gem up, made the change, re-ran my specs, and the error went away as expected. So, am I truly insane, or did this change not get pushed in 0.4.1 like the changelog says?

**Comment by isaacseymour** [comment]
The PR included in 0.4.1 was #12 , but not this one. I'll push 0.4.2 to Rubygems now...

**Comment by isaacseymour** [comment]
@lleger - pushed in 0.4.2. Thanks for pointing this out!

**Comment by lleger** [comment]
:+1: Thanks

**Pull request merged**
